### ISSUE TITLE
请问如何回到正常窗口界面？

### ISSUE THREAD

**Issue by mingyanggit** [nulijiabei/xplay#1]
不好意思是新手不太会用树莓派，我安装进入之后，每次重启都是terminal界面了。请问如何回到正常窗口界面呀？以及如果完全卸载。谢谢。

**Comment by nulijiabei** [comment]
@mingyanggit 
因为 RPI4 使用 DRM 输出，需要关闭桌面，如果需要使用桌面直接 systemctl enable display-manager

**Comment by nulijiabei** [comment]
@mingyanggit 
移除文件 /usr/bin/xplay
移除文件 /usr/bin/xplayctl
移除文件 /etc/ld.so.conf.d/00-xplay.conf 
移除目录 /etc/xplay
移除目录 /usr/local/lib 中以下文件
libavcodec.so             
libavformat.so            
libSDL2_ttf-2.0.so.0.14.1    
libavcodec.so.57          
libavformat.so.57         
libSDL2-2.0.so.0             
libavcodec.so.57.107.100  
libavformat.so.57.83.100  
libSDL2-2.0.so.0.10.0        
libavdevice.so            
libavutil.so              
libswresample.so             
libavdevice.so.57         
libavutil.so.55           
libswresample.so.2           
libavdevice.so.57.10.100  
libavutil.so.55.78.100    
libswresample.so.2.9.100     
libavfilter.so            
libSDL2.so                
libswscale.so                
libavfilter.so.6          
libSDL2_ttf.so            
libswscale.so.4              
libavfilter.so.6.107.100  
libSDL2_ttf-2.0.so.0      
libswscale.so.4.8.100

**Comment by mingyanggit** [comment]
> @mingyanggit
> 因为 RPI4 使用 DRM 输出，需要关闭桌面，如果需要使用桌面直接 systemctl enable display-manager

我是 RPI4 B, 用的是systemctl start lightdm

**Comment by aslin3** [comment]
> 

RPI 3B+，安装xplay之后不能自动进入图形界面，使用systemctl start lightdm，可以自动进入图形界面了。
